apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-service-deployment
  labels:
    app: cicd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-app
  template:
    metadata:
      labels:
        app: cicd-app
    spec:
      nodeSelector:
        kubernetes.io/hostname: "ip-192-168-34-80.ec2.internal"

      containers:
        - name: cicd-app
          image: CONTAINER_IMAGE
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "1"

---

apiVersion: v1
kind: Service
metadata:
  name: cicd-service
spec:
  selector:
    app: cicd-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30001
  type: NodePort
  
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cicd-service-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cicd-service
                port:
                  number: 30001
                  